force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <label>Stripe Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/StripeCustomerID__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomer</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StripeCharge__c/StripeCharge__c.object-meta.xml
<CustomObject>
    <label>Stripe Charge</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>StripeCharge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeCharge__c/fields/Amount_Refunded__c.field-meta.xml
<CustomField>
    <fullName>Amount_Refunded__c</fullName>
    <label>Amount Refunded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Captured__c.field-meta.xml
<CustomField>
    <fullName>Captured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Captured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Failure_Message__c.field-meta.xml
<CustomField>
    <fullName>Failure_Message__c</fullName>
    <label>Failure Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Receipt_Id__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Id__c</fullName>
    <label>Receipt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Receipt_Url__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Url__c</fullName>
    <label>Receipt Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Refunded__c.field-meta.xml
<CustomField>
    <fullName>Refunded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refunded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>succeeded</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipName>StripeCharges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/StripeChargeId__c.field-meta.xml
<CustomField>
    <fullName>StripeChargeId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Stripe Charge Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ChargesHandler.cls
public class ChargesHandler implements IStripeWebhooks {
    public static void parseResponse(Map<String,Object> postData, Map<String,String>paramsMap){
        
        DateTime startTime = System.now();
        String stripeAccId = paramsMap.get('AccId');
        List<StripeCharge__c> upsrtChr = new List<StripeCharge__c>();
        
        Map<String,Object> chargeMap = (Map<String,Object>)postData.get('data');
        StripeChargeObj chrObj = JsonToStripeObject.jsonToCharge((Map<String,Object>)chargeMap.get('object'));
        
        StripeCharge__c charge = new StripeCharge__c();
        charge.StripeChargeId__c = chrObj.Id;
        charge.Created__c = chrObj.created;
        
        List<Stripe_Customer__c> SfCust = [SELECT id,StripeCustomerID__c FROM Stripe_Customer__c 
                                           WHERE StripeCustomerID__c =: chrObj.customer];
        
        charge.Stripe_Customer__c = SfCust.isEmpty() ? null : SfCust[0].Id;
        charge.Amount__c = chrObj.amount/100;
        charge.Amount_Refunded__c = chrObj.amount_refunded;
        charge.Captured__c = chrObj.captured;
        charge.Currency__c = chrObj.curncy;
        charge.Description__c = chrObj.description;
        charge.Failure_Message__c = chrObj.failure_msg;
        charge.Invoice_Id__c = chrObj.invoice;
        charge.Order_Id__c = chrObj.order;
        charge.Paid__c = chrObj.paid;
        charge.Receipt_Id__c = chrObj.receipt_num;
        charge.Receipt_Url__c = chrObj.receipt_url;
        charge.Refunded__c = chrObj.refunded;
        charge.Status__c = chrObj.status;
        
        upsrtChr.add(charge);
        
        RestResponse res = RestContext.response;
        try {
            Database.UpsertResult[] resultsChr = Database.upsert(upsrtChr, StripeCharge__c.StripeChargeId__c);
            
            res.addHeader('Content-Type', 'application/json');
            res.responseBody = Blob.valueOf('{"inserted/updated stripe Subscription" : {"id":"'+resultsChr[0].getId()+'"}}');
            res.statusCode = 200;
            
            StripeWebhookHandler.createLog(postData, resultsChr[0].getId(), startTime, System.now());
        } catch (Exception ex) {
            Logger.capture(ex);
            res.addHeader('Content-Type', 'application/json');
            res.responseBody = Blob.valueOf(JSON.serializePretty(ex.getMessage()));
            res.statusCode = 500;
            
            StripeWebhookHandler.createLog(postData, 'error: '+ex.getMessage().abbreviate(200), startTime, System.now());
        }            
    }
}