force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <label>Stripe Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeCharge__c/StripeCharge__c.object-meta.xml
<CustomObject>
    <label>Stripe Charge</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>StripeCharge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeCharge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>succeeded</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StripeCharge__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipName>StripeCharges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripePaymentMethod__c/StripePaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Stripe Payment Method</label>
    <nameField>
        <displayFormat>SPM-{0000}</displayFormat>
        <label>Stripe Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripePaymentMethod__c/fields/Last_Four_Digits__c.field-meta.xml
<CustomField>
    <fullName>Last_Four_Digits__c</fullName>
    <label>Last Four Digits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StripePaymentMethod__c/fields/Stripe_Customer__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Customer</label>
    <referenceTo>Stripe_Customer__c</referenceTo>
    <relationshipName>StripePaymentMethods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripePlan__c/StripePlan__c.object-meta.xml
<CustomObject>
    <label>Stripe Plan</label>
    <nameField>
        <label>StripePlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripePlan__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>StripePlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripePlan__c/fields/Stripe_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Subscription</label>
    <referenceTo>StripeSubscription__c</referenceTo>
    <relationshipLabel>Stripe Plans</relationshipLabel>
    <relationshipName>Stripe_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripeSubscription__c/StripeSubscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000}</displayFormat>
        <label>Stripe Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeSubscription__c/fields/StripePlanAmount__c.field-meta.xml
<CustomField>
    <fullName>StripePlanAmount__c</fullName>
    <formula>Plan__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stripe Plan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/StripeCustomerViewController.cls
public class StripeCustomerViewController 
{	
    @AuraEnabled
    public static List<StripeSubscription__c> fetchStripeSubscription(Id custId)
    {
        List<StripeSubscription__c> subscriptionList = [SELECT Id, StripePlanAmount__c, Stripe_Customer__c 
                                                FROM StripeSubscription__c WHERE Stripe_Customer__c =:custId];
        
        return subscriptionList;
    }
    
    @AuraEnabled
    public static List<StripeCharge__c> fetchStripeCharge(Id custId)
    {
        List<StripeCharge__c> chargeList = [SELECT Id,Name,Amount__c,Status__c,Created__c FROM StripeCharge__c WHERE Stripe_Customer__c =:custId];
        return chargeList;
    }
    
    @AuraEnabled
    public static List<ProductWrap> fetchProducts(Id custId)
    {
        List<ProductWrap> prdList = new List<ProductWrap>();
        
        for(StripePlan__c pln: [SELECT Id,Name,Product__r.Name, Interval_Count__c 
                                FROM StripePlan__c 
                                WHERE Stripe_Subscription__r.Stripe_Customer__c =:custId])
        {
            ProductWrap prd = new ProductWrap();
            prd.ProductId = pln.Id;
            prd.ProductName = pln.Product__r.Name;
            prd.ProductSize = pln.Interval_Count__c;
            
            prdList.add(prd);
        }
        
        return prdList;
    }
    
    @AuraEnabled
    public static List<StripePaymentMethod__c> fetchStripePaymentMethods(Id custId)
    {
        List<StripePaymentMethod__c> stripePayMthds = [SELECT Id, Last_Four_Digits__c, Brand__c 
                                                       FROM StripePaymentMethod__c 
                                                       WHERE Stripe_Customer__c =:custId];
        
        return stripePayMthds;
    }
    
    Public class ProductWrap{
        @AuraEnabled
        public String ProductId{get;set;}
        @AuraEnabled
        public String ProductName{get;set;}
        @AuraEnabled
        public Decimal ProductSize{get;set;}
    }
}