force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <label>Stripe Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/StripeAccountID__c.field-meta.xml
<CustomField>
    <fullName>StripeAccountID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>StripeAccountID</label>
    <referenceTo>Stripe_Account__c</referenceTo>
    <relationshipLabel>Stripe Customers</relationshipLabel>
    <relationshipName>Stripe_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Customer__c/fields/StripeCustomerID__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>StripeCustomer</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StripeCustomer.cls
public class StripeCustomer {

    
    @auraEnabled
    public static String syncStripeCustomer(Id stripeCustId) 
    {	
        String respString;
        
        if(String.isNotEmpty(stripeCustId))
        {
         	Stripe_Customer__c custList = [SELECT Id, StripeCustomerID__c, StripeAccountID__r.API_Secret__c FROM Stripe_Customer__c WHERE Id =:stripeCustId];
        	
            if(!Test.isRunningTest()) {
            	respString = StripeApiCallout.doCallout(custList.StripeAccountID__r.API_Secret__c,'customers/'+custList.StripeCustomerID__c);   
            }else {
                respString = MockHttpResponseSingleCustomerGenerator.jsonstr;
            }
            
        	
            try {
                updateCustomerWithRelatedObj(respString);
            } catch (Exception ex) {
                Logger.capture(ex);
                return ex.getMessage();
            }

            return 'Success';   
        }else {
            return 'No id to process';
        }
    }
    
    public static void updateCustomerWithRelatedObj(String respJson)
    {
        Map<String, Object> respMap = (Map<String, Object>)JSON.deserializeUntyped(respJson);
        System.debug(respMap);
        
        StripeCustomerObj customer = JsonToStripeObject.jsonToCustomer(respMap);

        StripeDmlHandler.customerObjDml(new List<StripeCustomerObj>{customer});    
    }
}