force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeEvent__c/StripeEvent__c.object-meta.xml
<CustomObject>
    <label>Stripe Event</label>
    <nameField>
        <displayFormat>Stripe Event - {0000}</displayFormat>
        <label>Stripe Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeEvent__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/EndProcessingTime__c.field-meta.xml
<CustomField>
    <fullName>EndProcessingTime__c</fullName>
    <label>End Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StripeSiteSettings__c/StripeSiteSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stripe Site Settings</description>
    <label>Stripe Site Settings</label>
</CustomObject>

force-app/main/default/objects/StripeSiteSettings__c/fields/StripeApiEndpoint__c.field-meta.xml
<CustomField>
    <fullName>StripeApiEndpoint__c</fullName>
    <label>StripeApiEndpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/StripeSiteSettings__c/fields/WebhookUrl__c.field-meta.xml
<CustomField>
    <fullName>WebhookUrl__c</fullName>
    <description>Webhook url to host apex classes</description>
    <label>WebhookUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/StripeControllerTest.cls
@isTest
public class StripeControllerTest {

    @isTest
    private static void testStripeController(){
        
        Stripe_Account__c acc = TestUtils.createStripeAccount();
        
        List<StripeEvent__c> eventList = new List<StripeEvent__c>();
        
        for(Integer i = 0; i<5; i++) {
            StripeEvent__c evnt = new StripeEvent__c();
            evnt.Action__c = 'account.created account.updated';
            evnt.Data__c = 'data=[test data]';
            evnt.EndProcessingTime__c = System.today();
            
            eventList.add(evnt);
        }
        insert eventList;
        
        StripeSiteSettings__c settingObj=new StripeSiteSettings__c();
        settingObj.StripeApiEndpoint__c='https://api.stripe.com/v1/';
        settingObj.WebhookUrl__c='https://stripe-api-developer-edition.ap15.force.com/';
        insert settingObj;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        
        StripeController.fetchAccounts();
        StripeController.createWebhook(acc.Id);
        StripeController.fetchAccountBalance(acc.Id);
        StripeController.runbatch(acc.Id, 'SyncAllStripeCustomerBatch');
        StripeController.fetchSiteSettings();
        StripeController.saveSiteSettings(settingObj);
        StripeController.verifySiteUrl('www.google.com');
        StripeController.fetchEventLogs();
        
        Test.stopTest();
    }
    
    @isTest
    private static void runbatch2() {
        
        Stripe_Account__c acc=TestUtils.createStripeAccount();
        StripeController.runbatch(acc.Id, 'SyncAllStripeProductsBatch');
    }
    
    @isTest
    private static void runbatch3() {
        
        Stripe_Account__c acc=TestUtils.createStripeAccount();
        StripeController.runbatch(acc.Id, 'SyncAllStripeTaxRatesBatch');
    }
    
    @isTest
    private static void runbatch4() {
        
        Stripe_Account__c acc=TestUtils.createStripeAccount();
        StripeController.runbatch(acc.Id, 'SyncAllStripeChargesBatch');
    }
}