force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <label>Stripe Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/StripeAccountID__c.field-meta.xml
<CustomField>
    <fullName>StripeAccountID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>StripeAccountID</label>
    <referenceTo>Stripe_Account__c</referenceTo>
    <relationshipLabel>Stripe Customers</relationshipLabel>
    <relationshipName>Stripe_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripePlan__c/StripePlan__c.object-meta.xml
<CustomObject>
    <label>Stripe Plan</label>
    <nameField>
        <label>StripePlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripePlan__c/fields/Stripe_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Subscription</label>
    <referenceTo>StripeSubscription__c</referenceTo>
    <relationshipLabel>Stripe Plans</relationshipLabel>
    <relationshipName>Stripe_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StripeSubscription__c/StripeSubscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000}</displayFormat>
        <label>Stripe Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StripeCustomerViewControllerTest.cls
@isTest
public class StripeCustomerViewControllerTest {

    @isTest
    private static void testFetchStripe(){
        
        Stripe_Account__c acc=TestUtils.createStripeAccount();
        
        Stripe_Customer__c cust = new Stripe_Customer__c();
        cust.StripeAccountID__c=acc.Id;
        insert cust;
        
        //String jsonStr='{"id":"plan_GVcvwakJhpKlRD","object":"plan","active":true,"aggregate_usage":null,"amount":10000,"amount_decimal":"10000","billing_scheme":"per_unit","created":1578478935,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"nickname":"testing month","product":"prod_GVctSX10Usl6FE","tiers":null,"tiers_mode":null,"transform_usage":null,"trial_period_days":17,"usage_type":"licensed"}';
        //StripePlanObj planObj=JsonToStripeObject.jsonToPlan((Map<String,Object>)JSON.deserializeUntyped(jsonStr));
        
        StripeSubscription__c sub = new StripeSubscription__c();
        sub.Stripe_Customer__c = cust.Id;
        insert sub;
        
       
        StripePlan__c pln = new StripePlan__c();
        pln.Stripe_Subscription__c = sub.Id;
        insert pln;
        
        Test.startTest();
        StripeCustomerViewController.fetchProducts(cust.Id);
        StripeCustomerViewController.fetchStripeCharge(cust.Id);
        StripeCustomerViewController.fetchStripePaymentMethods(cust.Id);
        StripeCustomerViewController.fetchStripeSubscription(cust.Id);
        Test.stopTest();
    }
}