force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/Stripe_Customer__c.object-meta.xml
<CustomObject>
    <label>Stripe Customer</label>
    <nameField>
        <label>Stripe Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Customer__c/fields/StripeAccountID__c.field-meta.xml
<CustomField>
    <fullName>StripeAccountID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>StripeAccountID</label>
    <referenceTo>Stripe_Account__c</referenceTo>
    <relationshipLabel>Stripe Customers</relationshipLabel>
    <relationshipName>Stripe_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StripeCustomerTest.cls
@isTest
public class StripeCustomerTest {

    @isTest
    private static void testStripeCustomer(){
        
        Stripe_Account__c acc=TestUtils.createStripeAccount();
        
        Stripe_Customer__c cust=new Stripe_Customer__c();
        cust.StripeAccountID__c=acc.Id;

        insert cust;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseSingleCustomerGenerator());
        
        Test.startTest();
       	 StripeCustomer.syncStripeCustomer(cust.Id);
        Test.stopTest();
    }
}