force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeSiteSettings__c/StripeSiteSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stripe Site Settings</description>
    <label>Stripe Site Settings</label>
</CustomObject>

force-app/main/default/objects/StripeSiteSettings__c/fields/WebhookUrl__c.field-meta.xml
<CustomField>
    <fullName>WebhookUrl__c</fullName>
    <description>Webhook url to host apex classes</description>
    <label>WebhookUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CreateWebhooksTest.cls
@isTest
public class CreateWebhooksTest {

    @testsetup static void setupdata() {
                
        StripeSiteSettings__c site = new StripeSiteSettings__c();
        site.WebhookUrl__c = 'https://www.google.com/';
        
        insert site;
		
        Stripe_Account__c acc = new Stripe_Account__c();
        acc.Name = 'Test Stripe Account';
        acc.Active__c = true;
        acc.API_Key__c = 'testapikey';
        acc.API_Secret__c = 'testsecretkey';
        
        Insert acc;

    }
    
    @isTest static void createTest() {        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Stripe_Account__c acc = [SELECT Id FROM Stripe_Account__c WHERE Name = 'Test Stripe Account'];
        Test.startTest();
        	CreateWebhooks.create(acc.Id);
        Test.stopTest();
    }
}