force-app/main/default/objects/StripeEvent__c/StripeEvent__c.object-meta.xml
<CustomObject>
    <label>Stripe Event</label>
    <nameField>
        <displayFormat>Stripe Event - {0000}</displayFormat>
        <label>Stripe Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StripeEvent__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/EndProcessingTime__c.field-meta.xml
<CustomField>
    <fullName>EndProcessingTime__c</fullName>
    <label>End Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/PrimaryResource__c.field-meta.xml
<CustomField>
    <fullName>PrimaryResource__c</fullName>
    <label>Primary Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/ResourceRecord__c.field-meta.xml
<CustomField>
    <fullName>ResourceRecord__c</fullName>
    <label>Resource Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/ResourceType__c.field-meta.xml
<CustomField>
    <fullName>ResourceType__c</fullName>
    <label>Resource Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/SecondaryResource__c.field-meta.xml
<CustomField>
    <fullName>SecondaryResource__c</fullName>
    <label>Secondary Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEvent__c/fields/StartProcessingTime__c.field-meta.xml
<CustomField>
    <fullName>StartProcessingTime__c</fullName>
    <label>Start Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/StripeWebhookHandler.cls
public class StripeWebhookHandler {

    public static void createLog(Map<String,Object> webhk, String objId, Datetime startTime, Datetime endTime) {
        
        List<String> rsource = new List<String>();

        StripeEvent__c evnt = new StripeEvent__c();

        evnt.Type__c = (String)webhk.get('type');
        rsource = evnt.Type__c.split('\\.');
        
        if(rsource.size() == 2 ) {
            
            evnt.PrimaryResource__c = rsource[0];
            evnt.Action__c = rsource[1];
        }else if(rsource.size() == 3 ) {
            
            evnt.PrimaryResource__c = rsource[0];
            evnt.SecondaryResource__c = rsource[1];
            evnt.Action__c = rsource[2];
        }

        Map<String, Object> obj = (Map<String, Object>)webhk.get('data');
        Map<String, Object> objData = (Map<String,Object>)obj.get('object');
        evnt.ResourceType__c = (String)objData.get('object');
        evnt.ResourceId__c = (String)objData.get('id');
        evnt.ResourceRecord__c = objId;

        String objDataStr = String.valueOf(objData);
        evnt.Data__c = objDataStr.abbreviate(131072);
        evnt.StartProcessingTime__c = startTime;
        evnt.EndProcessingTime__c = endTime;

        insert evnt;
    }
}